### ISSUE TITLE
Replying to him should have the same effect as mentioning him

### ISSUE THREAD

**Issue by LuisMayo** [LuisMayo/marte-markov-telegram-bot#4]

**Comment by LuisMayo** [comment]
It shouldn't because sometimes people use reply to react to its messages

**Comment by sarah278** [comment]
I think this would be a great Idea, but it should be optional and by default off. Only groupadmins should be able to enable/disable this by a command. Probably you could implement a configurable cooldown, after x replys ignore for time x all replys.
